In [1]:
import pandas as pd

In [15]:
df = pd.read_csv('./CUSTOMER_SULAWESI.csv')

In [17]:
df['invoice_date'] = pd.to_datetime(df['invoice_date'])
df['year'] = df['invoice_date'].dt.year.astype('Int64')
df['month'] = df['invoice_date'].dt.month

In [19]:
df_customer_monthly = (
    df
    .groupby(["customer_name", "year", "month"], as_index=False)
    .agg(
        total_revenue=("total_price", "sum"),
        total_invoice=("invoice_number", "nunique")
    )
)

In [25]:
df_customer_monthly.nlargest(10, 'total_invoice')

              customer_name  year  month  total_revenue  total_invoice
82  MANTUL PETSHOP MAKASSAR  2026      7    410402101.0             43
81  MANTUL PETSHOP MAKASSAR  2026      6    109034970.0             36
64           MANTUL PETSHOP  2025      7    135989774.0             33
65           MANTUL PETSHOP  2025      8    107789754.0             31
68           MANTUL PETSHOP  2025     11    160089696.0             31
83  MANTUL PETSHOP MAKASSAR  2026      8     60797424.0             25
84  MANTUL PETSHOP MAKASSAR  2026      9     53555726.0             25
66           MANTUL PETSHOP  2025      9    105325752.0             24
67           MANTUL PETSHOP  2025     10     83435962.0             23
69           MANTUL PETSHOP  2025     12    104357106.0             22

In [27]:
df_final_customer = (
    df_customer_monthly
    .groupby("customer_name", as_index=False)
    .agg(
        total_revenue=("total_revenue", "sum"),
        total_invoice=("total_invoice", "sum"),
        median_invoice_per_bulan=("total_invoice", "median"),
        median_revenue_per_bulan=("total_revenue", "median")
    )
)

In [28]:
df_final_customer.nlargest(10, 'median_invoice_per_bulan')

,customer_name,total_revenue,total_invoice,median_invoice_per_bulan,median_revenue_per_bulan
22,MANTUL PETSHOP,1.264873e+09,256,22.0,90212808.0
23,MANTUL PETSHOP MAKASSAR,7.738742e+08,153,22.0,57176575.0
48,SL.003 - CV. MAKASSAR SAFARI,2.158113e+09,120,3.0,48342720.0
6,AWAL PETSHOPE AND CARE SENGKANG,1.098082e+07,2,2.0,10980817.0
7,BORONG PETSHOP,1.089288e+06,2,2.0,1089288.0
15,INTI POULTRI,2.605104e+06,4,2.0,1302552.0
26,MINNIE PETSHOPE PARE PARE,9.346869e+06,2,2.0,9346869.0
47,SL.002 - HEI HEI PETSHOP,9.075782e+08,66,2.0,26092080.0
50,SL.005 - JURAGAN PETSHOP KENDARI,4.991059e+09,108,2.0,139551300.0
57,SUPER POLTRY,5.161080e+07,5,2.0,19917600.0